---

- name: "Generate Baseline Config(s)"
  hosts: all
  connection: local
  gather_facts: no
  
  tasks:
    - name: Create Template storage directory within the staging directory
      file: path=./staging/{{ inventory_hostname }}/ state=directory

    - name: Generate baseline j2 template
      template: src=./{{ baselines.baseline }} dest=./staging/{{ inventory_hostname }}/{{ inventory_hostname }}_baseline.cfg

    - name: Append templates together to create final baseline configuration file
      assemble: src=./staging/{{ inventory_hostname }}/ dest=./complete/{{ inventory_hostname }}_FINAL.cfg

    - name: Delete Staging Directories
      file: path=./staging/{{ inventory_hostname }}/ state=absent
